os: windows
language: shell

script:
    - ls /
    - #set
    - choco install cygwin --params "/NoStartMenu"
    - choco install cyg-get && /c/ProgramData/chocolatey/bin/cyg-get.bat dos2unix patch unzip automake make bzip2 libsqlite-3-devel libtool gcc-g++ openssl-devel wget gcc-core cygwin-devel
# imake makedepend libarchive13 libcom_err2 libcurl4 libexpat1 libext2fs2 libgssapi_krb5_2 libjsoncpp19 libk5crypto3 libkrb5_3 libkrb5support0 liblz4_1 libnghttp2_14 libopenldap2_4_2 librhash0 libsasl2-devel libsasl2_3 libslang2 libsqlite3-devel libsqlite3_0 libssh2_1 libuv1 perl-TimeDate cmake
    - ls -la && echo 2 && ls -la / && echo 3 && ls -la /c && echo 4 && ls -la /c/ProgramData && echo 5 && ls -la /c/ProgramData/chocolatey && echo 6 && ls -la /c/ProgramData/chocolatey/bin/ && echo 7 && ls -la /c/tools/cygwin/ && echo 8 && ls -la /c/tools/cygwin/bin
    - ./setup-cygwin-packages.cmd
#    - ./test.cmd
#    - ./travis-step2-libetpan.cmd
    - ./travis-step3-cmocka.cmd
