os: windows
language: shell

script:
  - choco install nodejs.install
  - export PATH=/c/Users/travis/.cargo/bin:$PATH && cd /c/ProgramData/chocolatey/bin && wget --quiet https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe && ./rustup-init.exe -y --default-toolchain nightly
  - export PATH=/c/Users/travis/.cargo/bin:$PATH && rustc --version
  - export PATH=/c/Users/travis/.cargo/bin:/c/Program\ Files/nodejs:$PATH && cd $TRAVIS_BUILD_DIR && git clone https://github.com/deltachat/deltachat-node --recursive && cd deltachat-node && npm install && npm link
  - cd $TRAVIS_BUILD_DIR && git clone --recursive https://github.com/deltachat/deltachat-desktop && cd deltachat-desktop && export PATH=/c/Users/travis/.cargo/bin:/c/Program\ Files/nodejs:$PATH && npm link deltachat-node && npm install && echo build deltachat dekstop windows && npm run build && echo test deltachat windows && npm run test
  - cd $TRAVIS_BUILD_DIR/deltachat-desktop && npm run dist || true
  - cd $TRAVIS_BUILD_DIR/deltachat-desktop && cd dist && mv win-unpacked ../release/ && cd .. && 7z a -tzip -r deltachat-win.zip release && mv deltachat-win.zip $TRAVIS_BUILD_DIR/

deploy:
  provider: releases
  api_key:
    secure: YC0nuOOrmtNZe5J7c3g2QeaqjK36eW0tb/Nv/oSXSaYAW3c5t0OPlkRlwZjXtqci21oQ9vxRfFXnCIPMAHg0eG2dejO66uKQ/4X42qTSluJ4PIIGiSAHO7KffL9CKRwJhK40lIlUacG6wvGNLJVfOV7jw57o1yCztI6AIR7THR9CvQ+8R1G7sB4XSKPCbQxRb1j6nHAzxXnrnv9L7zZK1yINd3gMmcOr2hiCUd6VR1Gijw3+mGtZ2Tuq0q06ikrFy6qB2sRAM6NpiAa7zQmSODX/G9qFsKq73JwVgDFSJ81roRRI69pZOBbYhVpeI03YyA6QxWNEmLuX0hn8pMpyokjW1wL+KXtbgtFdSJMFv6dixKMw+tLCNmq6/yzod7q0aNsQn1DmQdfmEh/g3fYbV5IlhwRlh7thyQAo8AkLYsDtXv/6GYy8tGJcyA1rp46tSTTonqv4ueZ5Pna7K0yKJ5z+dl8qyjc5vTWqdOLWJRjWFkHNB5Iq7nEqK5MKvTMNM4hQL3J+PbA37NJxUPkbQfKswx+Sagb0hB/L8DGxbc2oYfX93AUaD0z3o5Vro0bOgsC1+53iS7FpyOikwOWKFOJ/2wyDX95GCIUdFWWW5ytP9nairWAKbOO6uh/btP09qiPzgUc8mFQ+f5TcdQn0qRwfwopQxALOQ5O+cARlFwc=
  file: 
    - deltachat-win.zip
  prerelease: true
  skip_cleanup: true
  draft: true
  on:
    repo: homdx/deltachat-windows
